frameworkVersion: ">=1.2.0 <2.0.0"

service: upload-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  profile: laardee
  region: us-east-1
  environment:
    SERVERLESS_STAGE: ${opt:stage, self:provider.stage}
    SERVERLESS_PROJECT: ${self:service}
    SERVERLESS_REGION: ${opt:region, self:provider.region}
    SESSIONS_TABLE_NAME: ${self:provider.environment.SERVERLESS_PROJECT}-sessions-${self:provider.environment.SERVERLESS_STAGE}
    SOURCE_BUCKET:
      Fn::ImportValue: video-service-source-bucket-${self:provider.environment.SERVERLESS_STAGE}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - S3:ListBucket
      - S3:GetObject
      - S3:PutObject
      Resource: "*"
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: arn:aws:dynamodb:${self:provider.environment.SERVERLESS_REGION}:*:*
    - Effect: Allow
      Action:
      - SNS:*
      Resource: arn:aws:sns:${self:provider.environment.SERVERLESS_REGION}:*:*
package:
  exclude:
    - test/**
    - .git/**

functions:
  signed-url:
    handler: signed-url/index.handler
    events:
      - http:
          path: signed-url
          method: get
          cors: true
    timeout: 20

plugins:
  - serverless-mocha-plugin
  - serverless-webpack
  - serverless-offline

custom:
  serverless-mocha-plugin:
    functionTemplate: templates/function.ejs
  webpackIncludeModules: true

resources:
  Resources:
    SessionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.SESSIONS_TABLE_NAME}